name: SSH
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
     - uses: actions/checkout@v1

     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://proxy.xiaofeiya.tk/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: 1nW8yaMtIE9qf8OrTSmmm1c9SXR_6tegwg6RajZe5bF4B8U6J
        USER_PASS: mike
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 6h
